### PR TITLE
Windows build documentation

### PR DESCRIPTION
**Pull request by Joaopmoliveira**
Simple .md file explaining in small steps how to build the library.

### CODE REVIEW

**Comment by jpbruyere** [comment]
Very nice, several remarks.
For a technical paper, I prefer to avoid first person sentences (I, we), be more direct, but your level of detail is quiet good.
GLFW is only required if you want to build the samples, we may provide an inline link to their site (https://www.glfw.org/)
You don't tell about them (the samples), are they built? We should explain at least the launch of one of them to check if everything is good.
Is he operation of having freetype built with lcd font complicated? Maybe we should provide some detail on what it is for, and how to enable it. (https://en.wikipedia.org/wiki/Subpixel_rendering).
Very nice for a first approach, I will merge it tomorrow evening. Don't hesitate to put links to pertinent details or site about what you're talking (vcpkg).

**Comment by Joaopmoliveira** [comment]
I am still trying to set up the samples (i am having some issues with the code, today I think I can push through)! Will work on the language and the links for the important things. To make theses changes do I commit on my repository on github and ask for a new pull request or do I change them and they are automatically included in this pull request?

**Comment by jpbruyere** [comment]
ok, so I let you continue pushing on this branch, and we'll merge when you're done.

**Comment by jpbruyere** [comment]
I'm thinking it would be a must to have vkvg built by vcpkg: `vcpkg install vkvg`, what about you're test on samples? are they ok?

**Comment by Joaopmoliveira** [comment]
Not ok, the debug build is working properly, but the executable with the samples crashes on runtime due to a null pointer, still trying to find why that is the case.

**Comment by Joaopmoliveira** [comment]
vcpkg seems like a good solution to the library!

**Comment by jpbruyere** [comment]
so you can run the samples when building with 'Debug' build, but there failed with null pointer on Release?

**Comment by Joaopmoliveira** [comment]
The Debug release for the samples also crashes at runtime and the Release build fails. I cannot find the error. Is there a way for us to try and solve this problem so that I can advance to the vkvg tutorials? If you have the time of course!

**Comment by jpbruyere** [comment]
if you run from vs in Debug mode, you should see which call is causing the crash, have you some info on where it stop, and which program stop? I suspect maybe vulkan installation. Give me any error message you encounter.

**Comment by jpbruyere** [comment]
I've made a vcpkg port of vkvg (vcpkg install vkvg), it's ok if I only built in in the vcpkg environment, but if I try to build all the depencies, it fails.

**Comment by jpbruyere** [comment]
The first thing I would try is to install the vulkan sdk system wide with the official download at: https://vulkan.lunarg.com/sdk/home, and set the VULKAN_SDK env variable to 'C:/VulkanSDK/1.1.130.0' (include version directory). It builds on appveyor with vcpkg like this.

**Comment by Joaopmoliveira** [comment]
I installed the Vulkan library from Lunar so that is not the problem. You were correct that one of the problems resided the linker flag -lm, there was a warning due to it. But the main cause of failure resided with the following piece of code: 
```bach
inline bool vkengine_should_close (VkEngine e) {
    return glfwWindowShouldClose (e->window);
}
```
If I remove the inline keyword everything works. Now I am not sure if this is something to do with the c++ compiler doing crazy things by itself or not..
Nevertheless the release version is now working properly (without the inline) but the debug function is still crashing.

**Comment by jpbruyere** [comment]
I had also to remove 'inline' statements everywhere to succeed compiling with appveyor on win64. Tests were not built there, so I forgot this inline. I'll push it to master. I've started investigating how to handle inline function on windows, but I've not yet a solution.

**Comment by jpbruyere** [comment]
Could you check that on your machine the '__inline' statement is going well, if yes I will replace function decoration with a platform dependant inline.

**Comment by Joaopmoliveira** [comment]
On the windows [website](https://docs.microsoft.com/en-us/cpp/cpp/inline-functions-cpp?redirectedfrom=MSDN&view=vs-2019) they state :
```batch
The inline keyword is available only in C++. The __inline and __forceinline keywords are available in both C and C++. For compatibility with previous versions, _inline and _forceinline are synonyms for __inline, and __forceinline unless compiler option /Za (Disable language extensions) is specified. 
```
But even with __inline I still get 
```batch
tests_common.lib(test.obj) : error LNK2019: unresolved external symbol vkengine_should_close referenced in function perform_test
```

**Comment by jpbruyere** [comment]
It looks like it is more easy to inline on linux, every thing is fine without it? Was the vulkan sdk installation mandatory to have it working?

**Comment by Joaopmoliveira** [comment]
Everything works, both release and debug! Will start working on the samples. To you want me to test the vcpkg branch?

**Comment by Joaopmoliveira** [comment]
Without the inline*
What if we define the body of the function in the same place as the declaration? That way in windows it will be a single transnational unit and it will not give an error.

**Comment by jpbruyere** [comment]
For sure if we have vkvg integrated directly into the vcpkg system, it would be great. You may test it if you want, I think it's quiet straight forward.

**Comment by jpbruyere** [comment]
Note that for error handling, which is not complete for now, I will make a function callbacks instead of printing to stderr or stdout, I'll make it within those days.

**Comment by Joaopmoliveira** [comment]
In regards to error handling, why no mimic the vulkan library if possible? I find their methods very clear, consistent and simple.

**Comment by jpbruyere** [comment]
That's it, registering a callback and forwarding errors only if someone has register a function"

**Comment by jpbruyere** [comment]
I've merge manually into master, I allowed myself to edit your tutorial, but don't hesitate to also change my edits if you find better ways to explain. Also can you confirm that installing vulkan with vcpkg is sufficient, and the lunarg sdk is optional.

**Comment by Joaopmoliveira** [comment]
I will, sorry, still understanding how to integrate your samples into the vulkan tutorial. Once I have finished this I will work on it. Btw how do you prefer that I contribute to the library? Because this integration seemed clunky!

**Comment by jpbruyere** [comment]
It's always easier to start programing from scratch than to enter the code of someone else. Feel confident, Roma was not built in a day. Only those who do nothing, do no errors. Every intervention is welcome, even clunky one, that bring me another viewpoint. Don't hesitate to show me code and ask questions, there's always more idea in 2 heads than in one. For your tutorials, let's use the wiki, and keep the source tree for rough technical docs .

**Pull request closed without merging**
