### PR TITLE
Add vkvg_status_to_string

### PR DESCRIPTION
**Pull request by Rubo3**
The order is the same of that in the enum. What would you like to get from `VKVG_STATUS_INVALID_IMAGE` and `VKVG_STATUS_INVALID_SURFACE`?

Also, I put the definition on `vkvg_context.c` but I don't think that's appropriate. Where should we put it? Should we do like Cairo and create a `vkvg_misc.c` file?

### CODE REVIEW

**Comment by jpbruyere** [comment]
I've started the list with what existed in cairo, you may remove unused entries.

**Comment by jpbruyere** [comment]
See compile errors in check, their must all be green.

**Comment by Rubo3** [comment]
All green now.

**Comment by Rubo3** [comment]
`NO_CURRENT_POINT` and `INVALID_INDEX` technically are not used, but on the docs I found `vkvg_rel_curve_to` [should](https://github.com/jpbruyere/vkvg/blob/99e8a561f43eba0b1550d88912581fb5e2e55a08/include/vkvg.h#L1086) use the first one, while `vkvg_pattern_get_color_stop_count` [should](https://github.com/jpbruyere/vkvg/blob/99e8a561f43eba0b1550d88912581fb5e2e55a08/include/vkvg.h#L1770) use the second one.

**Comment by Rubo3** [comment]
Please see #102 and tell me if that's acceptable.

**Comment by Rubo3** [comment]
I think it's done now.

**Comment by Rubo3** [comment]
I mean I think it's ready to be merged, or doesn't it?

**Pull request merged**
