### PR TITLE
Added stdarg.h inclusion

### LINKED ISSUE #81: stdarg.h include
As revealed here #79 by @Rubo3 , stdarg.h is indirectly included by vulkan wayland, so a clean inclusion is required.

### PR DESCRIPTION
**Pull request by Rubo3**
Should close #81 .

### CODE REVIEW

**Comment by jpbruyere** [comment]
I also use stdarg for the LOG macro, on windows, stdlib.h is also required, we should check on other platforms if stdlib.h is also required...

**Comment by jpbruyere** [comment]
so, because stdio is in context_internal, we can go with a simple stdarg include in context_internal.h

**Comment by Rubo3** [comment]
Moved. I put it after the `vkvg_*` inclusions as `stdio.h` is needed before `stdarg.h`.

**Comment by Rubo3** [comment]
On the last commit message I meant `vkvg_context_internal.h`, not `vkvg_context_internal.c`, sorry.

**Comment by jpbruyere** [comment]
thats vkvg_internal.h, sorry, I'm working on multithreading...

**Review by jpbruyere — APPROVED** [review]

**Comment by jpbruyere** [comment]
thank you for the fix :-)

**Pull request merged**
