### PR TITLE
compile fixes for macOS

### PR DESCRIPTION
**Pull request by fzwoch**
Some small changes to make the project compile on macOS.

Note that running it will not work due to missing MoltenVK/Metal support of `VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN`. It would be nice to have a fallback path with `VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP` or similar in these cases. Is that feasable?

### CODE REVIEW

**Comment by jpbruyere** [comment]
Is there any hope to have Triangle fans support in MoltenVK in near future? It's use in vkvg to handle Even/Odd fill of polygons, and the algorithm used makes triangle fans support mandatory. The quick solution I see is to make it possible to disable Even/Odd fill on macOS.

**Comment by fzwoch** [comment]
There are some occasions in the MoltenVK SDK like this:

https://github.com/KhronosGroup/MoltenVK/blob/26ff3e594a3524b94e1ca90a26cd69df5fba8e21/MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm#L419

So it seems like there is no good match for that operation mode on Apple's Metal layer. And I assume MoltenVK wants to be more like a translation layer, and not an emulation layer. Therefore I suspect they will keep it that way unless future versions of Metal include something that comes close to triangle fans.

It would be nice if there at least was some switch to let it run in less optimized way (If that is what the quick solution would be about). Being able it to run slowly is a start compared to be not be able to run it at all.

**Comment by jpbruyere** [comment]
I've just pushed on master the disabling of even/odd fill on macOS so vkvg should runs on mac. Tanks a lot for your pull request.

**Comment by fzwoch** [comment]
Thanks. It builds and runs just fine now on master branch.

Any side effects expected for drawing? Because here is the current SVG tiger rendered from the test application:

svg

**Comment by jpbruyere** [comment]
Yes, the svg rendering with NanoSvg runs only with even/odd fills, I guess the nanosvg library itself produce even/odd fills only.

**Comment by jpbruyere** [comment]
The work to have even/odd with triangle list is to add the use of the Index buffer in the _poly_fill() method and add the indices as the fans would produce with the contour points. I'll put it on my TODO list.

**Pull request merged**
